version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/
    overwrite: yes

hooks:
  AfterInstall:
    - location: ./scripts/stop.sh
  ApplicationStart:
    - location: ./scripts/deploy.sh
      timeout: 60
      runas: ec2-user