name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: groom-test-eris
  DOCKER_TAG_VERSION: ${{ github.run_number }}
  DESTINATION_FILE: groom-test-docker.tar
  ZIP_FILE: groom-test-docker.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag groom-test-docker:$DOCKER_TAG_VERSION

    - name: Docker image to file
      run: docker save groom-test-docker:$DOCKER_TAG_VERSION > $DESTINATION_FILE

    - name: make zip
      run: zip -qq -r ./$ZIP_FILE .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload s3
      run: aws s3 cp $ZIP_FILE s3://$S3_BUCKET_NAME/

    - name: Code deploy
      run: aws deploy create-deployment --application-name groom-code-deploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name groom-code-deploy-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$ZIP_FILE